export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const TOGGLE_CART_HIDDEN = 'TOGGLE_CART_HIDDEN';
export const CLEAR_CART = 'CLEAR_CART';